-- MySQL to SQLite:
-- 1. Convert "AUTO_INCREMENT" to "AUTOINCREMENT"
-- 2. Delete "\s+COMMENT\s+'.+?'"

DROP TABLE IF EXISTS `Cart`;
CREATE TABLE `Cart` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`UserSN` INT NOT NULL COMMENT '使用者序號' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CourseSN` INT NOT NULL COMMENT '課程序號' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '購物車';

DROP TABLE IF EXISTS `Category`;
CREATE TABLE `Category` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT '名稱',
	`Intro` text NOT NULL COMMENT '簡介'
) COMMENT '類別';

DROP TABLE IF EXISTS `Configuration`;
CREATE TABLE `Configuration` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Key` text NOT NULL UNIQUE COMMENT '鍵',
	`Value` text NOT NULL COMMENT '值'
) COMMENT '配置';

DROP TABLE IF EXISTS `Coupon`;
CREATE TABLE `Coupon` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT '',
	`Instruction` text NOT NULL COMMENT '說明',
	`WhenIssued` DATETIME NOT NULL COMMENT '發行日期',
	`WhenStarted` DATETIME NOT NULL COMMENT '開始日期',
	`WhenEnded` DATETIME NOT NULL COMMENT '結束日期'
) COMMENT '優惠券';

DROP TABLE IF EXISTS `Course`;
CREATE TABLE `Course` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Title` text NOT NULL COMMENT '',
	`Intro` text NOT NULL COMMENT '',
	`Syllabus` text NOT NULL COMMENT '課綱',
	`Price` INT NOT NULL COMMENT '',
	`WhenApplied` DATETIME NOT NULL COMMENT '',
	`WhenLaunched` DATETIME NULL COMMENT '',
	`TeacherUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`SysopUserSN` INT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '課程';

DROP TABLE IF EXISTS `CourseCoupon`;
CREATE TABLE `CourseCoupon` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CouponSN` INT NOT NULL COMMENT '' REFERENCES `Coupon` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '課程優惠券';

DROP TABLE IF EXISTS `CourseDomain`;
CREATE TABLE `CourseDomain` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`DomainSN` INT NOT NULL COMMENT '' REFERENCES `Domain` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '課程領域';

DROP TABLE IF EXISTS `Course.Review`;
CREATE TABLE `CourseReview` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Rating` INT NOT NULL COMMENT '',
	`Content` text NOT NULL COMMENT '',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`LearnerUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '課程評論';

DROP TABLE IF EXISTS `CourseTag`;
CREATE TABLE `CourseTag` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`TagSN` INT NOT NULL COMMENT '' REFERENCES `Tag` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '課程標籤';

DROP TABLE IF EXISTS `DiscussionIssue`;
CREATE TABLE `DiscussionIssue` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Title` text NOT NULL COMMENT '',
	`Content` INT NOT NULL COMMENT '',
	`WhenCreated` DATETIME NOT NULL COMMENT '',
	`WhenLastEdited` DATETIME NOT NULL COMMENT '',
	`WhenDeleted` DATETIME NULL COMMENT '',
	`LearnerCourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`AuthorUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`SolutionDiscussionIssueCommentSN` INT NULL COMMENT '' REFERENCES `DiscussionIssueComment` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `DiscussionIssueComment`;
CREATE TABLE `DiscussionIssueComment` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Content` INT NOT NULL COMMENT '',
	`DiscussionIssueSN` INT NOT NULL COMMENT '' REFERENCES `DiscussionIssue` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`ParentDiscussionIssueCommentSN` INT NULL COMMENT '' REFERENCES `DiscussionIssueComment` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `Domain`;
CREATE TABLE `Domain` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT '',
	`Intro` text NOT NULL COMMENT ''
) COMMENT '領域';

DROP TABLE IF EXISTS `File`;
CREATE TABLE `File` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT '',
	`Extension` text NOT NULL COMMENT '',
	`ContentType` text NOT NULL COMMENT '',
	`ContentHash` text NOT NULL COMMENT '',
	`WhenUploaded` DATETIME NOT NULL COMMENT '',
	`WhenDeleted` DATETIME NOT NULL COMMENT '',
	`UploaderUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '檔案';

DROP TABLE IF EXISTS `Homework`;
CREATE TABLE `Homework` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Title` text NOT NULL COMMENT '',
	`Content` INT NULL COMMENT '',
	`WhenCreated` INT NOT NULL COMMENT '',
	`WhenLastEdited` INT NULL COMMENT '',
	`WhenPosted` INT NULL COMMENT '',
	`WhenDeleted` INT NULL COMMENT '',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`AssignerUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `OAuthProvider`;
CREATE TABLE `OAuth` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT ''
) COMMENT '開放授權供應商';

DROP TABLE IF EXISTS `Post`;
CREATE TABLE `Post` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Identifer` text NOT NULL COMMENT '',
	`Title` text NOT NULL COMMENT '',
	`Intro` text NULL COMMENT '',
	`Content` text NOT NULL COMMENT '',
	`WhenCreated` DATETIME NOT NULL COMMENT '',
	`WhenLastEdited` DATETIME NULL COMMENT '',
	`WhenPublished` DATETIME NULL COMMENT '',
	`AuthorUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '文章';

DROP TABLE IF EXISTS `PostCategory`;
CREATE TABLE `PostCategory` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`PostSN` INT NOT NULL COMMENT '' REFERENCES `Post` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CategorySN` INT NOT NULL COMMENT '' REFERENCES `Category` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '文章分類';

DROP TABLE IF EXISTS `Promotion`;
CREATE TABLE `Promotion` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` INT NOT NULL COMMENT '',
	`Percentage` INT NOT NULL COMMENT '',
	`WhenStarted` DATETIME NULL COMMENT '',
	`WhenEnded` DATETIME NULL COMMENT '',
	`Amount` INT NULL COMMENT '',
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`PromoterUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '促銷';

DROP TABLE IF EXISTS `LearnerCoupon`;
CREATE TABLE `LearnerCoupon` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`LearnerUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CouponSN` INT NOT NULL COMMENT '' REFERENCES `Coupon` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '學員優惠券';

DROP TABLE IF EXISTS `LearnerCourse`;
CREATE TABLE `LearnerCourse` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Percentage` INT NOT NULL COMMENT '',
	`LearnerUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '學員課程';

DROP TABLE IF EXISTS `LearnerHomework`;
CREATE TABLE `LearnerHomework` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Content` text NOT NULL COMMENT '',
	`Score` INT NULL COMMENT '',
	`Pinned` INT NOT NULL DEFAULT '0' COMMENT '',
	`Comment` text NULL COMMENT '',
	`LearnerUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`HomeworkSN` INT NOT NULL COMMENT '' REFERENCES `Homework` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`TeacherUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `LearnerHomeworkFile`;
CREATE TABLE `LearnerHomeworkFile` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Content` text NOT NULL COMMENT '',
	`LearnerHomeworkSN` INT NOT NULL COMMENT '' REFERENCES `LearnerHomework` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`FileSN` INT NOT NULL COMMENT '' REFERENCES `File` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `Tag`;
CREATE TABLE `Tag` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Name` text NOT NULL COMMENT ''
) COMMENT '';

DROP TABLE IF EXISTS `TeacherCourse`;
CREATE TABLE `TeacherCourse` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`TeacherUserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '講師課程';

DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`Username` text NOT NULL COMMENT '',
	`PasswordHash` text NOT NULL COMMENT '密碼雜湊值',
	`E-mail` text NOT NULL COMMENT '電子信箱',
	`FirstName` text NOT NULL COMMENT '名字',
	`LastName` text NOT NULL COMMENT '姓氏',
	`Nickname` text NULL COMMENT '暱稱',
	`Phone` text NULL COMMENT '',
	`Birthday` DATETIME NULL COMMENT '出生日期',
	`WhenRegistered` DATETIME NOT NULL COMMENT '註冊日期',
	`WhenDeactivated` DATETIME NOT NULL COMMENT '',
	`Teachable` INT NOT NULL DEFAULT '0' COMMENT '',
	`OAuthProviderSN` INT NULL COMMENT '開放授權供應商序號',
	`GrantorUserSN` INT NOT NULL COMMENT '授權者序號'
) COMMENT '使用者';

DROP TABLE IF EXISTS `UserLikeCourse`;
CREATE TABLE `UserLikeCourse` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`UserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`CourseSN` INT NOT NULL COMMENT '' REFERENCES `Course` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';

DROP TABLE IF EXISTS `UserLikePost`;
CREATE TABLE `UserLikePost` (
	`SN` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '序號',
	`UserSN` INT NOT NULL COMMENT '' REFERENCES `User` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE,
	`PostSN` INT NOT NULL COMMENT '' REFERENCES `Post` (`SN`) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT '';
